services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SCRIPT: build:prod
    image: graduation-project/uaa:latest
    container_name: uaa-frontend
    restart: unless-stopped
    ports:
      - "5793:8080"
