export type AgentCmsLocale = "en" | "vi";

const copy = {
  en: {
    messages: {
      title: "Messages",
      searchPlaceholder: "Search",
      selectConversationTitle: "Select a conversation",
      selectConversationDescription:
        "Choose a thread from the left sidebar to review messages and reply.",
      loadingConversationsTitle: "Loading conversations",
      loadingConversationsDescription:
        "Fetching your latest chats and unread activity.",
      conversationsErrorTitle: "Could not load conversations",
      conversationsErrorDescription:
        "The inbox is temporarily unavailable. Retry to reconnect.",
      loadingConversationTitle: "Loading conversation",
      loadingConversationDescription:
        "Fetching message history and participant details.",
      conversationErrorTitle: "Could not load this conversation",
      conversationErrorDescription:
        "The chat service is temporarily unavailable. Retry to restore the thread.",
      conversationNotFoundTitle: "Conversation not found",
      conversationNotFoundDescription:
        "This thread may have been removed or you may no longer have access to it.",
      noConversationsTitle: "No conversations yet",
      noConversationsDescription:
        "When a buyer or agent starts a chat, it will appear here.",
      noMessagesTitle: "No messages yet",
      noMessagesDescriptionPrefix: "Start the conversation with",
      noMessagesDescriptionFallback: "this contact",
      activeNow: "Active now",
      typing: "Typing...",
      inputPlaceholder: "Type a message...",
      tryAgain: "Try again",
      defaultUser: "User",
    },
    profile: {
      noDescription: "<p>No public description has been added yet.</p>",
      bankWarningTitle: "Warning",
      bankWarningDescription:
        "Your profile is not complete. Please complete your bank information to continue.",
      roleBadge: "Real Estate Agent",
      registerPasskey: "Register Passkey",
      changePassword: "Change Password",
      editProfile: "Edit Profile",
      sections: {
        contactInfo: "Contact Info",
        bankInfo: "Bank Info",
        professionalProfile: "Professional Profile",
        description: "Description",
        specialization: "Specialization",
        workingArea: "Working Area",
        documents: "Documents",
      },
      fields: {
        phoneNumber: "Phone Number",
        email: "Email",
        address: "Address",
        bankAccountName: "Bank Account Name",
        bankAccountNumber: "Bank Account Number",
        bankName: "Bank Name",
        experience: "Experience",
        years: "years",
        rating: "Rating",
        taxCode: "Tax Code",
        certificateNumber: "Certificate Number",
        identityCard: "Identity Card",
        businessLicense: "Business License",
      },
      identity: {
        title: "Legal Identity",
        sensitive: "Sensitive Information",
        fullName: "Full Name",
        idNumber: "ID Number",
        gender: "Gender",
        dateOfBirth: "Date of Birth",
      },
      completion: {
        complete: "Complete",
        eyebrow: "Profile Completion",
        title: "Complete your profile",
        descriptionPrefix: "You have completed",
        descriptionMiddle: "profile checkpoints.",
        descriptionSuffix:
          "Fill in the missing information to make your profile look stronger to clients and appear more complete across the platform.",
        completed: "Completed",
        remaining: "Remaining",
      },
      passwordModal: {
        title: "Change Password",
        oldPassword: "Old Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        oldPasswordRequired: "Old password is required",
        newPasswordRequired: "New password is required",
        confirmPasswordRequired: "Confirm password is required",
        cancel: "Cancel",
        submit: "Change Password",
      },
    },
    landlord: {
      pageTitle: "Landlords",
      pageSubtitle: "Manage your landlord contacts",
      addLandlord: "Add Landlord",
      searchPlaceholder: "Search",
      empty: "No landlords found",
      columns: {
        name: "Name",
        email: "Email",
        phone: "Phone",
        action: "Action",
      },
      alert: {
        title: "Delete",
        description: "Are you sure you want to delete this landlord?",
        action: "Delete",
        cancel: "Cancel",
      },
      modal: {
        addTitle: "Add Landlord",
        editTitle: "Update Landlord",
        addAction: "Add Landlord",
        editAction: "Update Landlord",
        fullName: "Full Name",
        emailAddress: "Email Address",
        phoneNumber: "Phone Number",
        address: "Address",
        placeholders: {
          fullName: "e.g. John Doe",
          emailAddress: "john.doe@example.com",
          phoneNumber: "0123456789",
          address: "e.g. 123 Main St, Springfield",
        },
        validation: {
          fullName: "Full name is required",
          email: "Email is required",
          emailInvalid: "Please enter a valid email address",
          phoneNumber: "Phone number is required",
          address: "Address is required",
        },
      },
      detail: {
        back: "Back",
        notFound: "Landlord not found",
        title: "Landlord Details",
        subtitle: "View information and real estate holdings",
        memberSince: "Member since",
        realEstate: "Real Estate",
        emptyProperties: "No real estate properties found for this landlord.",
        columns: {
          title: "Title",
          type: "Type",
          location: "Location",
          price: "Price",
          status: "Status",
          date: "Date",
        },
        statuses: {
          sale: "For Sale",
          rent: "For Rent",
        },
      },
    },
  },
  vi: {
    messages: {
      title: "Tin nhắn",
      searchPlaceholder: "Tìm kiếm",
      selectConversationTitle: "Chọn một cuộc trò chuyện",
      selectConversationDescription:
        "Chọn một luồng ở thanh bên trái để xem và trả lời tin nhắn.",
      loadingConversationsTitle: "Đang tải cuộc trò chuyện",
      loadingConversationsDescription:
        "Đang tải danh sách chat gần nhất và hoạt động chưa đọc.",
      conversationsErrorTitle: "Không thể tải danh sách cuộc trò chuyện",
      conversationsErrorDescription:
        "Hộp thư tạm thời không khả dụng. Hãy thử kết nối lại.",
      loadingConversationTitle: "Đang tải cuộc trò chuyện",
      loadingConversationDescription:
        "Đang tải lịch sử tin nhắn và thông tin người tham gia.",
      conversationErrorTitle: "Không thể tải cuộc trò chuyện này",
      conversationErrorDescription:
        "Dịch vụ chat đang tạm thời không khả dụng. Hãy thử tải lại luồng chat.",
      conversationNotFoundTitle: "Không tìm thấy cuộc trò chuyện",
      conversationNotFoundDescription:
        "Luồng chat này có thể đã bị xóa hoặc bạn không còn quyền truy cập.",
      noConversationsTitle: "Chưa có cuộc trò chuyện nào",
      noConversationsDescription:
        "Khi người mua hoặc môi giới bắt đầu chat, cuộc trò chuyện sẽ hiển thị tại đây.",
      noMessagesTitle: "Chưa có tin nhắn nào",
      noMessagesDescriptionPrefix: "Hãy bắt đầu cuộc trò chuyện với",
      noMessagesDescriptionFallback: "liên hệ này",
      activeNow: "Đang hoạt động",
      typing: "Đang nhập...",
      inputPlaceholder: "Nhập tin nhắn...",
      tryAgain: "Thử lại",
      defaultUser: "Người dùng",
    },
    profile: {
      noDescription: "<p>Chưa có mô tả công khai nào được thêm.</p>",
      bankWarningTitle: "Cảnh báo",
      bankWarningDescription:
        "Hồ sơ của bạn chưa hoàn chỉnh. Vui lòng bổ sung thông tin ngân hàng để tiếp tục.",
      roleBadge: "Môi giới bất động sản",
      registerPasskey: "Đăng ký Passkey",
      changePassword: "Đổi mật khẩu",
      editProfile: "Chỉnh sửa hồ sơ",
      sections: {
        contactInfo: "Thông tin liên hệ",
        bankInfo: "Thông tin ngân hàng",
        professionalProfile: "Hồ sơ chuyên môn",
        description: "Mô tả",
        specialization: "Chuyên môn",
        workingArea: "Khu vực hoạt động",
        documents: "Tài liệu",
      },
      fields: {
        phoneNumber: "Số điện thoại",
        email: "Email",
        address: "Địa chỉ",
        bankAccountName: "Tên chủ tài khoản",
        bankAccountNumber: "Số tài khoản",
        bankName: "Tên ngân hàng",
        experience: "Kinh nghiệm",
        years: "năm",
        rating: "Đánh giá",
        taxCode: "Mã số thuế",
        certificateNumber: "Số chứng chỉ",
        identityCard: "Căn cước công dân",
        businessLicense: "Giấy phép kinh doanh",
      },
      identity: {
        title: "Thông tin pháp lý",
        sensitive: "Thông tin nhạy cảm",
        fullName: "Họ và tên",
        idNumber: "Số CCCD",
        gender: "Giới tính",
        dateOfBirth: "Ngày sinh",
      },
      completion: {
        complete: "Hoàn thành",
        eyebrow: "Mức độ hoàn thiện hồ sơ",
        title: "Hoàn thiện hồ sơ của bạn",
        descriptionPrefix: "Bạn đã hoàn thành",
        descriptionMiddle: "mốc hồ sơ.",
        descriptionSuffix:
          "Hãy điền phần thông tin còn thiếu để hồ sơ trông chuyên nghiệp hơn với khách hàng và đầy đủ hơn trên toàn nền tảng.",
        completed: "Đã hoàn thành",
        remaining: "Còn thiếu",
      },
      passwordModal: {
        title: "Đổi mật khẩu",
        oldPassword: "Mật khẩu cũ",
        newPassword: "Mật khẩu mới",
        confirmPassword: "Xác nhận mật khẩu",
        oldPasswordRequired: "Mật khẩu cũ là bắt buộc",
        newPasswordRequired: "Mật khẩu mới là bắt buộc",
        confirmPasswordRequired: "Xác nhận mật khẩu là bắt buộc",
        cancel: "Hủy",
        submit: "Đổi mật khẩu",
      },
    },
    landlord: {
      pageTitle: "Chủ nhà",
      pageSubtitle: "Quản lý danh sách chủ nhà của bạn",
      addLandlord: "Thêm chủ nhà",
      searchPlaceholder: "Tìm kiếm",
      empty: "Không tìm thấy chủ nhà nào",
      columns: {
        name: "Tên",
        email: "Email",
        phone: "Số điện thoại",
        action: "Thao tác",
      },
      alert: {
        title: "Xóa",
        description: "Bạn có chắc muốn xóa chủ nhà này không?",
        action: "Xóa",
        cancel: "Hủy",
      },
      modal: {
        addTitle: "Thêm chủ nhà",
        editTitle: "Cập nhật chủ nhà",
        addAction: "Thêm chủ nhà",
        editAction: "Cập nhật chủ nhà",
        fullName: "Họ và tên",
        emailAddress: "Địa chỉ email",
        phoneNumber: "Số điện thoại",
        address: "Địa chỉ",
        placeholders: {
          fullName: "ví dụ: Nguyễn Văn A",
          emailAddress: "nguyenvana@example.com",
          phoneNumber: "0123456789",
          address: "ví dụ: 123 Nguyễn Huệ, Quận 1",
        },
        validation: {
          fullName: "Họ và tên là bắt buộc",
          email: "Email là bắt buộc",
          emailInvalid: "Vui lòng nhập địa chỉ email hợp lệ",
          phoneNumber: "Số điện thoại là bắt buộc",
          address: "Địa chỉ là bắt buộc",
        },
      },
      detail: {
        back: "Quay lại",
        notFound: "Không tìm thấy chủ nhà",
        title: "Chi tiết chủ nhà",
        subtitle: "Xem thông tin và tài sản bất động sản",
        memberSince: "Tham gia từ",
        realEstate: "Bất động sản",
        emptyProperties:
          "Không có bất động sản nào được liên kết với chủ nhà này.",
        columns: {
          title: "Tiêu đề",
          type: "Loại",
          location: "Vị trí",
          price: "Giá",
          status: "Trạng thái",
          date: "Ngày tạo",
        },
        statuses: {
          sale: "Đang bán",
          rent: "Cho thuê",
        },
      },
    },
  },
} as const;

export const getAgentCmsLocale = (locale?: string): AgentCmsLocale =>
  locale?.toLowerCase().startsWith("vi") ? "vi" : "en";

export const getAgentCmsCopy = (locale?: string) =>
  copy[getAgentCmsLocale(locale)];
