services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    restart: unless-stopped
