export const bankList = [
  { value: "ACB", label: "Ngân hàng Á Châu (ACB)" },
  { value: "BIDV", label: "Ngân hàng Đầu tư và Phát triển Việt Nam (BIDV)" },
  { value: "CTG", label: "Ngân hàng VietinBank" },
  { value: "TCB", label: "Ngân hàng Kỹ Thương (Techcombank)" },
  { value: "MBB", label: "Ngân hàng Quân Đội (MB Bank)" },
  {
    value: "AGRIBANK",
    label: "Ngân hàng Nông Nghiệp & Phát Triển Nông Thôn (Agribank)",
  },
  { value: "SHB", label: "Ngân hàng Sài Gòn – Hà Nội (SHB)" },
  { value: "TPB", label: "Ngân hàng TPBank" },
  { value: "HDB", label: "Ngân hàng HDBank" },
  { value: "SCB", label: "Ngân hàng Sài Gòn (SCB)" },
  { value: "BVB", label: "Ngân hàng Bắc Á (Bac A Bank)" },
  { value: "SEABANK", label: "Ngân hàng Đông Nam Á (SeABank)" },
  { value: "EXIMBANK", label: "Ngân hàng Xuất Nhập Khẩu (Eximbank)" },
  { value: "LIENVIETPOSTBANK", label: "Ngân hàng Bưu điện Liên Việt" },
  { value: "VPBANK", label: "Ngân hàng Việt Nam Thịnh Vượng (VPBank)" },
  { value: "SACOMBANK", label: "Ngân hàng Sài Gòn Thương Tín (Sacombank)" },
  { value: "VRB", label: "Ngân hàng Bảo Việt (BaoViet Bank)" },
  { value: "NAMABANK", label: "Ngân hàng Nam Á (Nam A Bank)" },
  { value: "OCB", label: "Ngân hàng Phương Đông (OCB)" },
  { value: "VIB", label: "Ngân hàng Quốc tế (VIB)" },
  { value: "SHINHAN", label: "Ngân hàng Shinhan Việt Nam" },
  { value: "Woori", label: "Ngân hàng Woori Việt Nam" },
  { value: "StandardChartered", label: "Ngân hàng Standard Chartered" },
  { value: "HSBC", label: "Ngân hàng HSBC" },
  { value: "Citibank", label: "Ngân hàng Citibank" },
  { value: "JPMorgan", label: "Ngân hàng JPMorgan Chase" },
];
