import type { Metadata } from "next";
import Sider from "@/components/layout/Sider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-10 h-screen">
      <div className="col-span-4">{children}</div>
      <div className="col-span-6 bg-[#F5F5F5] hidden md:block">
        <Sider />
      </div>
    </div>
  );
}
